### ISSUE TITLE
Some bar lines need to be treated as marks

### ISSUE THREAD

**Issue by danielgarthur** [danielgarthur/sbmufl#1]
Bar lines can appear both between neumes and above neumes. The current specification only provides for bar lines that appear between neumes.

I do not fully understand the rules for when a bar line may appear above a neume. 

Once understood, an additional set of bar line glyphs can be added to specification that will be positioned using mark-to-base positioning.

**Comment by basil** [comment]
> I do not fully understand the rules for when a bar line may appear above a neume.

I outlined most of the cases in https://github.com/danielgarthur/neanes/issues/144 (at least the ones I have been hitting in practice as I use the application).

In the case of a syneches elaphron (whether it is by itself, or combined with kentemata over an oligon), a barline usually makes no sense before the apostrophos. Rather it usually makes sense between the apostrophos and the elaphron, although it could go after the elaphron as well (say, if the elaphron had a klasma).

In the case of an ypporoe, the barline would be centered above the ypporoe if the new measure starts on the second beat. (If the ypporoe has a gorgon, the barline would be centered above the gorgon if the new measure starts on the second half-beat. What I really mean is the barline goes above the ypporoe if it applies to the second of the two descending gestures.)

In the case of kentemata beneath an oligon (with or without a klasma/gorgon) the barline would be centered above the oligon if the new measure starts with the oligon and not the kentemata. This is pretty much always the case, since it would make no sense for a measure to start with kentemata.

There might be other cases but these are by far the most common.
